
import java.awt.Image;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hraba
 */
public class AnaEkran extends javax.swing.JFrame {
    static int odemeTutari = 0;
    int fiyat=0;
    int italianoPizzaFiyatiKucuk = 250;
    int italianoPizzaFiyatiOrta = 350;
    int italianoPizzaFiyatiBuyuk = 450;
    int karisikPizzaFiyatiKucuk = 350;
    int karisikPizzaFiyatiOrta = 500;
    int karisikPizzaFiyatiBuyuk = 750;
    int turkishPizzaFiyatiKucuk = 320;
    int turkishPizzaFiyatiOrta = 450;
    int turkishPizzaFiyatiBuyuk = 600;
    int mexicanoPizzaFiyatiKucuk = 340;
    int mexicanoPizzaFiyatiOrta = 500;
    int mexicanoPizzaFiyatiBuyuk = 700;
    int nutellaPizzaFiyatiKucuk = 175;
    int nutellaPizzaFiyatiOrta = 250;
    int nutellaPizzaFiyatiBuyuk = 350;
    int patatesKizartmasiFiyati = 60;
    int soganHalkasiFiyati = 60;
    int nuggetFiyati = 75;
    int colaFiyati = 90;
    int fantaFiyati = 90;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AnaEkran.class.getName());

    /**
     * Creates new form AnaEkran
     */
    public static DefaultListModel<String> sepetModeli = new DefaultListModel<>();
    public AnaEkran() {
        initComponents();
        sepet1.setModel(sepetModeli);  
    
        // Pencereyi ekranı tamamen kaplayacak (tam ekran) modda başlatır
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); 
    
        // Kullanıcının pencere boyutunu değiştirmesini engeller (Kilitler)
        setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        anapanel = new javax.swing.JPanel();
        anabaslik = new javax.swing.JLabel();
        aciklamaBasligi = new javax.swing.JLabel();
        italaniopizza = new javax.swing.JLabel();
        italianoPizzaYazi = new javax.swing.JLabel();
        italianoPizzaFiyatYazisi = new javax.swing.JLabel();
        karisikPizza = new javax.swing.JLabel();
        karisikPizzaYazi = new javax.swing.JLabel();
        karisikPizzaFiyatYazisi = new javax.swing.JLabel();
        turkishPizza = new javax.swing.JLabel();
        turkishPizzaYazi = new javax.swing.JLabel();
        turkishPizzaFiyatYazisi = new javax.swing.JLabel();
        mexicanoPizza = new javax.swing.JLabel();
        mexicanoPizzaYazi = new javax.swing.JLabel();
        mexicanoPizzaFiyatYazisi = new javax.swing.JLabel();
        nutellaPizza = new javax.swing.JLabel();
        nutellaPizzaYazi = new javax.swing.JLabel();
        nutellaPizzaFiyatYazisi = new javax.swing.JLabel();
        italianoEkleButon = new javax.swing.JButton();
        italianoBilgiButon = new javax.swing.JButton();
        karisikEkleButon = new javax.swing.JButton();
        karisikBilgiButon = new javax.swing.JButton();
        turkishEkleButon = new javax.swing.JButton();
        turkishBilgiButon = new javax.swing.JButton();
        mexicanoEkleButon = new javax.swing.JButton();
        mexicanoBilgiButon = new javax.swing.JButton();
        nutellaEkleButon = new javax.swing.JButton();
        nutellaBilgiButon = new javax.swing.JButton();
        patatesKizartmasi = new javax.swing.JLabel();
        patatesKizartmasiYazi = new javax.swing.JLabel();
        soganHalkasi = new javax.swing.JLabel();
        soganHalkasiYazi = new javax.swing.JLabel();
        nugget = new javax.swing.JLabel();
        nuggetYazi = new javax.swing.JLabel();
        cola = new javax.swing.JLabel();
        colaYazi = new javax.swing.JLabel();
        fanta = new javax.swing.JLabel();
        fantaYazi = new javax.swing.JLabel();
        kizartmaFiyatYazisi = new javax.swing.JLabel();
        halkaFiyatYazisi = new javax.swing.JLabel();
        nuggetFiyatYazisi = new javax.swing.JLabel();
        colaFiyatYazisi = new javax.swing.JLabel();
        fantaFiyatYazisi = new javax.swing.JLabel();
        kizartmaEkleButon = new javax.swing.JButton();
        halkaEkleButon = new javax.swing.JButton();
        nuggetEkleButon = new javax.swing.JButton();
        colaEkleButon = new javax.swing.JButton();
        fantaEkleButon = new javax.swing.JButton();
        pizzaOlusturBasligi = new javax.swing.JLabel();
        pizzaOlusturButon = new javax.swing.JButton();
        sepetPaneli = new javax.swing.JPanel();
        sepetBaslik = new javax.swing.JLabel();
        sepetBaslik1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sepet1 = new javax.swing.JList<>();
        odemeButonu = new javax.swing.JButton();
        sepetSifirlaButonu = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 51));

        anapanel.setBackground(new java.awt.Color(51, 0, 51));
        anapanel.setForeground(new java.awt.Color(255, 255, 255));

        anabaslik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        anabaslik.setForeground(new java.awt.Color(255, 255, 255));
        anabaslik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anabaslik.setText("PİZZA SİPARİŞ SİSTEMİ");
        anabaslik.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        anabaslik.setName("anabaslik"); // NOI18N
        anabaslik.setPreferredSize(new java.awt.Dimension(900, 40));

        aciklamaBasligi.setForeground(new java.awt.Color(255, 255, 0));
        aciklamaBasligi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aciklamaBasligi.setText("Pizzanı seç dilediğin atıştırmalığı ve içeceği al beğenmezsen kendi pizzanı inşaa et!");

        italaniopizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/italianopizza.png"))); // NOI18N
        italaniopizza.setText("jLabel1");

        italianoPizzaYazi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        italianoPizzaYazi.setForeground(new java.awt.Color(255, 255, 255));
        italianoPizzaYazi.setText("İtaliano Pizza");

        italianoPizzaFiyatYazisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        italianoPizzaFiyatYazisi.setForeground(new java.awt.Color(255, 255, 0));
        italianoPizzaFiyatYazisi.setText("250 TL");

        karisikPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/karisikpizza.png"))); // NOI18N
        karisikPizza.setText("jLabel1");

        karisikPizzaYazi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        karisikPizzaYazi.setForeground(new java.awt.Color(255, 255, 255));
        karisikPizzaYazi.setText("Karışık Pizza");

        karisikPizzaFiyatYazisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        karisikPizzaFiyatYazisi.setForeground(new java.awt.Color(255, 255, 0));
        karisikPizzaFiyatYazisi.setText("350 TL");

        turkishPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/turkishpizza.png"))); // NOI18N
        turkishPizza.setText("jLabel1");

        turkishPizzaYazi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        turkishPizzaYazi.setForeground(new java.awt.Color(255, 255, 255));
        turkishPizzaYazi.setText("Turkish Pizza");

        turkishPizzaFiyatYazisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        turkishPizzaFiyatYazisi.setForeground(new java.awt.Color(255, 255, 0));
        turkishPizzaFiyatYazisi.setText("320 TL");

        mexicanoPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/mexicanopizza.png"))); // NOI18N
        mexicanoPizza.setText("jLabel1");

        mexicanoPizzaYazi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mexicanoPizzaYazi.setForeground(new java.awt.Color(255, 255, 255));
        mexicanoPizzaYazi.setText("Mexicano Pizza");

        mexicanoPizzaFiyatYazisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mexicanoPizzaFiyatYazisi.setForeground(new java.awt.Color(255, 255, 0));
        mexicanoPizzaFiyatYazisi.setText("340 TL");

        nutellaPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/nutellapizza.png"))); // NOI18N
        nutellaPizza.setText("jLabel1");

        nutellaPizzaYazi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nutellaPizzaYazi.setForeground(new java.awt.Color(255, 255, 255));
        nutellaPizzaYazi.setText("Nutella Pizza");

        nutellaPizzaFiyatYazisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nutellaPizzaFiyatYazisi.setForeground(new java.awt.Color(255, 255, 0));
        nutellaPizzaFiyatYazisi.setText("175 TL");

        italianoEkleButon.setText("EKLE");
        italianoEkleButon.addActionListener(this::italianoEkleButonActionPerformed);

        italianoBilgiButon.setBackground(new java.awt.Color(51, 102, 255));
        italianoBilgiButon.setText("BİLGİ");
        italianoBilgiButon.addActionListener(this::italianoBilgiButonActionPerformed);

        karisikEkleButon.setText("EKLE");
        karisikEkleButon.addActionListener(this::karisikEkleButonActionPerformed);

        karisikBilgiButon.setBackground(new java.awt.Color(51, 102, 255));
        karisikBilgiButon.setText("BİLGİ");
        karisikBilgiButon.addActionListener(this::karisikBilgiButonActionPerformed);

        turkishEkleButon.setText("EKLE");
        turkishEkleButon.addActionListener(this::turkishEkleButonActionPerformed);

        turkishBilgiButon.setBackground(new java.awt.Color(51, 102, 255));
        turkishBilgiButon.setText("BİLGİ");
        turkishBilgiButon.addActionListener(this::turkishBilgiButonActionPerformed);

        mexicanoEkleButon.setText("EKLE");
        mexicanoEkleButon.addActionListener(this::mexicanoEkleButonActionPerformed);

        mexicanoBilgiButon.setBackground(new java.awt.Color(51, 102, 255));
        mexicanoBilgiButon.setText("BİLGİ");
        mexicanoBilgiButon.addActionListener(this::mexicanoBilgiButonActionPerformed);

        nutellaEkleButon.setText("EKLE");
        nutellaEkleButon.addActionListener(this::nutellaEkleButonActionPerformed);

        nutellaBilgiButon.setBackground(new java.awt.Color(51, 102, 255));
        nutellaBilgiButon.setText("BİLGİ");
        nutellaBilgiButon.addActionListener(this::nutellaBilgiButonActionPerformed);

        patatesKizartmasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/patateskizartmasi.png"))); // NOI18N
        patatesKizartmasi.setText("jLabel1");

        patatesKizartmasiYazi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        patatesKizartmasiYazi.setForeground(new java.awt.Color(255, 255, 255));
        patatesKizartmasiYazi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patatesKizartmasiYazi.setText("Patates Kızartması");

        soganHalkasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/soganhalkasi.png"))); // NOI18N
        soganHalkasi.setText("jLabel1");

        soganHalkasiYazi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        soganHalkasiYazi.setForeground(new java.awt.Color(255, 255, 255));
        soganHalkasiYazi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        soganHalkasiYazi.setText("Soğan Halkası");

        nugget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/nugget.png"))); // NOI18N
        nugget.setText("jLabel1");

        nuggetYazi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nuggetYazi.setForeground(new java.awt.Color(255, 255, 255));
        nuggetYazi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nuggetYazi.setText("Nugget");

        cola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/cola1l.png"))); // NOI18N
        cola.setText("jLabel1");

        colaYazi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        colaYazi.setForeground(new java.awt.Color(255, 255, 255));
        colaYazi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colaYazi.setText("Cola 1L");

        fanta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/fanta1l.png"))); // NOI18N
        fanta.setText("jLabel1");

        fantaYazi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fantaYazi.setForeground(new java.awt.Color(255, 255, 255));
        fantaYazi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fantaYazi.setText("Fanta 1L");

        kizartmaFiyatYazisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kizartmaFiyatYazisi.setForeground(new java.awt.Color(255, 255, 0));
        kizartmaFiyatYazisi.setText("60 TL");

        halkaFiyatYazisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        halkaFiyatYazisi.setForeground(new java.awt.Color(255, 255, 0));
        halkaFiyatYazisi.setText("60 TL");

        nuggetFiyatYazisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nuggetFiyatYazisi.setForeground(new java.awt.Color(255, 255, 0));
        nuggetFiyatYazisi.setText("75 TL");

        colaFiyatYazisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        colaFiyatYazisi.setForeground(new java.awt.Color(255, 255, 0));
        colaFiyatYazisi.setText("90 TL");

        fantaFiyatYazisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fantaFiyatYazisi.setForeground(new java.awt.Color(255, 255, 0));
        fantaFiyatYazisi.setText("90 TL");

        kizartmaEkleButon.setBackground(new java.awt.Color(153, 51, 0));
        kizartmaEkleButon.setForeground(new java.awt.Color(255, 255, 255));
        kizartmaEkleButon.setText("EKLE");
        kizartmaEkleButon.addActionListener(this::kizartmaEkleButonActionPerformed);

        halkaEkleButon.setBackground(new java.awt.Color(153, 51, 0));
        halkaEkleButon.setForeground(new java.awt.Color(255, 255, 255));
        halkaEkleButon.setText("EKLE");
        halkaEkleButon.addActionListener(this::halkaEkleButonActionPerformed);

        nuggetEkleButon.setBackground(new java.awt.Color(153, 51, 0));
        nuggetEkleButon.setForeground(new java.awt.Color(255, 255, 255));
        nuggetEkleButon.setText("EKLE");
        nuggetEkleButon.addActionListener(this::nuggetEkleButonActionPerformed);

        colaEkleButon.setBackground(new java.awt.Color(153, 51, 0));
        colaEkleButon.setForeground(new java.awt.Color(255, 255, 255));
        colaEkleButon.setText("EKLE");
        colaEkleButon.addActionListener(this::colaEkleButonActionPerformed);

        fantaEkleButon.setBackground(new java.awt.Color(153, 51, 0));
        fantaEkleButon.setForeground(new java.awt.Color(255, 255, 255));
        fantaEkleButon.setText("EKLE");
        fantaEkleButon.addActionListener(this::fantaEkleButonActionPerformed);

        pizzaOlusturBasligi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pizzaOlusturBasligi.setForeground(new java.awt.Color(255, 255, 255));
        pizzaOlusturBasligi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pizzaOlusturBasligi.setText("<html>Seçenekleri beğenemedin mi?<br>Kendi pizzanı oluşturmaya ne dersin?</html>");

        pizzaOlusturButon.setBackground(new java.awt.Color(255, 204, 51));
        pizzaOlusturButon.setText("PİZZANI İNŞAA ET!");
        pizzaOlusturButon.addActionListener(this::pizzaOlusturButonActionPerformed);

        sepetPaneli.setBackground(new java.awt.Color(204, 102, 0));

        sepetBaslik.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        sepetBaslik.setForeground(new java.awt.Color(255, 255, 255));
        sepetBaslik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sepetBaslik.setText("SEPET");

        sepetBaslik1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        sepetBaslik1.setForeground(new java.awt.Color(255, 255, 255));
        sepetBaslik1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sepetBaslik1.setText("---------------------------------------");

        jScrollPane1.setViewportView(sepet1);

        odemeButonu.setBackground(new java.awt.Color(102, 102, 255));
        odemeButonu.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        odemeButonu.setForeground(new java.awt.Color(255, 255, 255));
        odemeButonu.setText("ÖDE");
        odemeButonu.addActionListener(this::odemeButonuActionPerformed);

        sepetSifirlaButonu.setBackground(new java.awt.Color(153, 0, 0));
        sepetSifirlaButonu.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        sepetSifirlaButonu.setForeground(new java.awt.Color(255, 255, 255));
        sepetSifirlaButonu.setText("SEPETİ SIFIRLA");
        sepetSifirlaButonu.addActionListener(this::sepetSifirlaButonuActionPerformed);

        javax.swing.GroupLayout sepetPaneliLayout = new javax.swing.GroupLayout(sepetPaneli);
        sepetPaneli.setLayout(sepetPaneliLayout);
        sepetPaneliLayout.setHorizontalGroup(
            sepetPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sepetPaneliLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sepetBaslik1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(sepetPaneliLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sepetPaneliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sepetPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sepetPaneliLayout.createSequentialGroup()
                        .addComponent(sepetBaslik)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sepetPaneliLayout.createSequentialGroup()
                        .addComponent(odemeButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sepetPaneliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sepetSifirlaButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sepetPaneliLayout.setVerticalGroup(
            sepetPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sepetPaneliLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(sepetBaslik, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepetBaslik1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(odemeButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepetSifirlaButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout anapanelLayout = new javax.swing.GroupLayout(anapanel);
        anapanel.setLayout(anapanelLayout);
        anapanelLayout.setHorizontalGroup(
            anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anabaslik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(aciklamaBasligi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(anapanelLayout.createSequentialGroup()
                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(anapanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(kizartmaFiyatYazisi)
                        .addGap(75, 75, 75)
                        .addComponent(halkaFiyatYazisi))
                    .addGroup(anapanelLayout.createSequentialGroup()
                        .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(anapanelLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(italianoPizzaYazi))
                            .addGroup(anapanelLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(italianoPizzaFiyatYazisi)))
                        .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, anapanelLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(karisikPizzaFiyatYazisi)
                                .addGap(142, 142, 142)
                                .addComponent(turkishPizzaFiyatYazisi)
                                .addGap(151, 151, 151)
                                .addComponent(mexicanoPizzaFiyatYazisi)
                                .addGap(150, 150, 150)
                                .addComponent(nutellaPizzaFiyatYazisi))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, anapanelLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(anapanelLayout.createSequentialGroup()
                                        .addComponent(karisikBilgiButon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(129, 129, 129)
                                        .addComponent(turkishBilgiButon, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(139, 139, 139)
                                        .addComponent(mexicanoBilgiButon, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(anapanelLayout.createSequentialGroup()
                                        .addComponent(karisikPizzaYazi)
                                        .addGap(100, 100, 100)
                                        .addComponent(turkishPizzaYazi)
                                        .addGap(108, 108, 108)
                                        .addComponent(mexicanoPizzaYazi)))
                                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(anapanelLayout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(nutellaPizzaYazi))
                                    .addGroup(anapanelLayout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(nutellaEkleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nutellaBilgiButon, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(anapanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(italianoEkleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(italianoBilgiButon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(karisikEkleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(turkishEkleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(mexicanoEkleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(anapanelLayout.createSequentialGroup()
                        .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(anapanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(anapanelLayout.createSequentialGroup()
                                        .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kizartmaEkleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(patatesKizartmasiYazi)
                                                .addComponent(patatesKizartmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(anapanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(soganHalkasi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(anapanelLayout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(halkaEkleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(soganHalkasiYazi))))
                                        .addGap(12, 12, 12)
                                        .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(anapanelLayout.createSequentialGroup()
                                                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(anapanelLayout.createSequentialGroup()
                                                        .addGap(23, 23, 23)
                                                        .addComponent(nuggetYazi))
                                                    .addComponent(nuggetEkleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(anapanelLayout.createSequentialGroup()
                                                        .addGap(29, 29, 29)
                                                        .addComponent(nuggetFiyatYazisi)))
                                                .addGap(53, 53, 53)
                                                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(colaYazi)
                                                    .addComponent(colaFiyatYazisi))
                                                .addGap(67, 67, 67)
                                                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(fantaFiyatYazisi)
                                                    .addComponent(fantaYazi)))
                                            .addGroup(anapanelLayout.createSequentialGroup()
                                                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(colaEkleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(anapanelLayout.createSequentialGroup()
                                                        .addComponent(nugget, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(cola, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(fantaEkleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fanta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(anapanelLayout.createSequentialGroup()
                                                .addGap(117, 117, 117)
                                                .addComponent(pizzaOlusturButon, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(pizzaOlusturBasligi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(anapanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(italaniopizza, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(karisikPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(turkishPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mexicanoPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nutellaPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addComponent(sepetPaneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        anapanelLayout.setVerticalGroup(
            anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anapanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(anabaslik, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aciklamaBasligi)
                .addGap(18, 18, 18)
                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(anapanelLayout.createSequentialGroup()
                        .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(italaniopizza, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(turkishPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mexicanoPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(karisikPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nutellaPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(italianoPizzaYazi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(karisikPizzaYazi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(turkishPizzaYazi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mexicanoPizzaYazi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nutellaPizzaYazi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(italianoPizzaFiyatYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(karisikPizzaFiyatYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(turkishPizzaFiyatYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mexicanoPizzaFiyatYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nutellaPizzaFiyatYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(italianoEkleButon)
                            .addComponent(italianoBilgiButon)
                            .addComponent(karisikEkleButon)
                            .addComponent(karisikBilgiButon)
                            .addComponent(turkishEkleButon)
                            .addComponent(turkishBilgiButon)
                            .addComponent(mexicanoEkleButon)
                            .addComponent(mexicanoBilgiButon)
                            .addComponent(nutellaEkleButon)
                            .addComponent(nutellaBilgiButon))
                        .addGap(37, 37, 37)
                        .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patatesKizartmasi)
                            .addComponent(soganHalkasi)
                            .addComponent(nugget)
                            .addComponent(cola)
                            .addComponent(fanta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patatesKizartmasiYazi)
                            .addComponent(soganHalkasiYazi)
                            .addComponent(nuggetYazi)
                            .addComponent(colaYazi)
                            .addComponent(fantaYazi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kizartmaFiyatYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(halkaFiyatYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuggetFiyatYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colaFiyatYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fantaFiyatYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kizartmaEkleButon)
                            .addComponent(halkaEkleButon)
                            .addComponent(nuggetEkleButon)
                            .addComponent(colaEkleButon)
                            .addComponent(fantaEkleButon))
                        .addGap(33, 33, 33)
                        .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pizzaOlusturBasligi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pizzaOlusturButon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sepetPaneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(817, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anapanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anapanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void italianoEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italianoEkleButonActionPerformed
    // 1. Radyo butonlarını ve "İtalyano Pizza" boyut fiyatlarını oluşturuyoruz
    javax.swing.JRadioButton radKucuk = new javax.swing.JRadioButton("<html><b>Küçük Boy</b><br>İnce kenar, hafif lezzet<br>Fiyat: 250 TL</html>");
    javax.swing.JRadioButton radOrta = new javax.swing.JRadioButton("<html><b>Orta Boy</b><br>İdeal seçim<br>Fiyat: 350 TL</html>");
    javax.swing.JRadioButton radBuyuk = new javax.swing.JRadioButton("<html><b>Büyük Boy</b><br>Doyurucu boy, bol malzeme<br>Fiyat: 450 TL</html>");

    // Varsayılan olarak küçük boy seçili gelsin
    radKucuk.setSelected(true);

    // 2. Sadece bir tanesinin seçilebilmesi için butonları grupluyoruz
    javax.swing.ButtonGroup boyGrubu = new javax.swing.ButtonGroup();
    boyGrubu.add(radKucuk);
    boyGrubu.add(radOrta);
    boyGrubu.add(radBuyuk);

    // 3. Seçeneklerin alt alta düzgün ve açıklamalı durması için bir Panel oluşturuyoruz
    javax.swing.JPanel panel = new javax.swing.JPanel();
    panel.setLayout(new java.awt.GridLayout(3, 1, 0, 10)); // 3 satır, 1 sütun, aralarında 10px boşluk
    panel.add(radKucuk);
    panel.add(radOrta);
    panel.add(radBuyuk);

    // 4. JOptionPane penceresini "AnaEkran" penceresine bağlı olarak açıyoruz
    int sonuc = javax.swing.JOptionPane.showConfirmDialog(
        AnaEkran.this, 
        panel, 
        "Italiano Pizza Boyut Seçimi", 
        javax.swing.JOptionPane.OK_CANCEL_OPTION, 
        javax.swing.JOptionPane.PLAIN_MESSAGE
    );

    // 5. Kullanıcı "Tamam" butonuna bastıysa seçimi kontrol ediyoruz
    if (sonuc == javax.swing.JOptionPane.OK_OPTION) {
        String secilenBoy = "";
        if (radKucuk.isSelected()) {
            secilenBoy = "Küçük";
            fiyat = 250;
            odemeTutari += italianoPizzaFiyatiKucuk;
        } else if (radOrta.isSelected()) {
            secilenBoy = "Orta";
            fiyat = 350;
            odemeTutari += italianoPizzaFiyatiOrta;
        } else if (radBuyuk.isSelected()) {
            secilenBoy = "Büyük";
            fiyat = 450;
            odemeTutari += italianoPizzaFiyatiBuyuk;
        }

    // 6. SEPETE EKLEME ALANI
        // sepet1 listesine bağlı olan sepetModeli'ne yeni elemanı ekliyoruz
        String urunBilgisi = "1x İtaliano Pizza (" + secilenBoy + ") - " + fiyat + " TL";
        sepetModeli.addElement(urunBilgisi);
        }
    }//GEN-LAST:event_italianoEkleButonActionPerformed

    private void karisikEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karisikEkleButonActionPerformed

    javax.swing.JRadioButton radKucuk = new javax.swing.JRadioButton("<html><b>Küçük Boy</b><br>İnce kenar, hafif lezzet<br>Fiyat: 350 TL</html>");
    javax.swing.JRadioButton radOrta = new javax.swing.JRadioButton("<html><b>Orta Boy</b><br>İdeal seçim<br>Fiyat: 500 TL</html>");
    javax.swing.JRadioButton radBuyuk = new javax.swing.JRadioButton("<html><b>Büyük Boy</b><br>Doyurucu boy, bol malzeme<br>Fiyat: 750 TL</html>");

    radKucuk.setSelected(true);

    javax.swing.ButtonGroup boyGrubu = new javax.swing.ButtonGroup();
    boyGrubu.add(radKucuk);
    boyGrubu.add(radOrta);
    boyGrubu.add(radBuyuk);

    javax.swing.JPanel panel = new javax.swing.JPanel();
    panel.setLayout(new java.awt.GridLayout(3, 1, 0, 10)); 
    panel.add(radKucuk);
    panel.add(radOrta);
    panel.add(radBuyuk);

    int sonuc = javax.swing.JOptionPane.showConfirmDialog(
        AnaEkran.this, 
        panel, 
        "Karışık Pizza Boyut Seçimi", 
        javax.swing.JOptionPane.OK_CANCEL_OPTION, 
        javax.swing.JOptionPane.PLAIN_MESSAGE
    );

    if (sonuc == javax.swing.JOptionPane.OK_OPTION) {
        String secilenBoy = "";
        if (radKucuk.isSelected()) {
            secilenBoy = "Küçük";
            fiyat = 350;
            odemeTutari += karisikPizzaFiyatiKucuk;
        } else if (radOrta.isSelected()) {
            secilenBoy = "Orta";
            fiyat = 500;
            odemeTutari += karisikPizzaFiyatiOrta;
        } else if (radBuyuk.isSelected()) {
            secilenBoy = "Büyük";
            fiyat = 750;
            odemeTutari += karisikPizzaFiyatiBuyuk;
        }

        String urunBilgisi = "1x Karışık Pizza (" + secilenBoy + ") - " + fiyat + " TL";
        sepetModeli.addElement(urunBilgisi);
        }      
    }//GEN-LAST:event_karisikEkleButonActionPerformed

    private void turkishEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turkishEkleButonActionPerformed

    javax.swing.JRadioButton radKucuk = new javax.swing.JRadioButton("<html><b>Küçük Boy</b><br>İnce kenar, hafif lezzet<br>Fiyat: 320 TL</html>");
    javax.swing.JRadioButton radOrta = new javax.swing.JRadioButton("<html><b>Orta Boy</b><br>İdeal seçim<br>Fiyat: 450 TL</html>");
    javax.swing.JRadioButton radBuyuk = new javax.swing.JRadioButton("<html><b>Büyük Boy</b><br>Doyurucu boy, bol malzeme<br>Fiyat: 600 TL</html>");

    radKucuk.setSelected(true);

    javax.swing.ButtonGroup boyGrubu = new javax.swing.ButtonGroup();
    boyGrubu.add(radKucuk);
    boyGrubu.add(radOrta);
    boyGrubu.add(radBuyuk);

    javax.swing.JPanel panel = new javax.swing.JPanel();
    panel.setLayout(new java.awt.GridLayout(3, 1, 0, 10)); 
    panel.add(radKucuk);
    panel.add(radOrta);
    panel.add(radBuyuk);

    int sonuc = javax.swing.JOptionPane.showConfirmDialog(
        AnaEkran.this, 
        panel, 
        "Turkish Pizza Boyut Seçimi", 
        javax.swing.JOptionPane.OK_CANCEL_OPTION, 
        javax.swing.JOptionPane.PLAIN_MESSAGE
    );

    if (sonuc == javax.swing.JOptionPane.OK_OPTION) {
        String secilenBoy = "";
        if (radKucuk.isSelected()) {
            secilenBoy = "Küçük";
            fiyat = 320;
            odemeTutari += turkishPizzaFiyatiKucuk;
        } else if (radOrta.isSelected()) {
            secilenBoy = "Orta";
            fiyat = 450;
            odemeTutari += turkishPizzaFiyatiOrta;
        } else if (radBuyuk.isSelected()) {
            secilenBoy = "Büyük";
            fiyat = 600;
            odemeTutari += turkishPizzaFiyatiBuyuk;
        }

        String urunBilgisi = "1x Turkish Pizza (" + secilenBoy + ") - " + fiyat + " TL";
        sepetModeli.addElement(urunBilgisi);
        } 
    }//GEN-LAST:event_turkishEkleButonActionPerformed

    private void mexicanoEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mexicanoEkleButonActionPerformed
    
    javax.swing.JRadioButton radKucuk = new javax.swing.JRadioButton("<html><b>Küçük Boy</b><br>İnce kenar, hafif lezzet<br>Fiyat: 340 TL</html>");
    javax.swing.JRadioButton radOrta = new javax.swing.JRadioButton("<html><b>Orta Boy</b><br>İdeal seçim<br>Fiyat: 500 TL</html>");
    javax.swing.JRadioButton radBuyuk = new javax.swing.JRadioButton("<html><b>Büyük Boy</b><br>Doyurucu boy, bol malzeme<br>Fiyat: 700 TL</html>");

    
    radKucuk.setSelected(true);

    javax.swing.ButtonGroup boyGrubu = new javax.swing.ButtonGroup();
    boyGrubu.add(radKucuk);
    boyGrubu.add(radOrta);
    boyGrubu.add(radBuyuk);

    javax.swing.JPanel panel = new javax.swing.JPanel();
    panel.setLayout(new java.awt.GridLayout(3, 1, 0, 10)); 
    panel.add(radKucuk);
    panel.add(radOrta);
    panel.add(radBuyuk);

    int sonuc = javax.swing.JOptionPane.showConfirmDialog(
        AnaEkran.this, 
        panel, 
        "Mexicano Pizza Boyut Seçimi", 
        javax.swing.JOptionPane.OK_CANCEL_OPTION, 
        javax.swing.JOptionPane.PLAIN_MESSAGE
    );

    if (sonuc == javax.swing.JOptionPane.OK_OPTION) {
        String secilenBoy = "";
        if (radKucuk.isSelected()) {
            secilenBoy = "Küçük";
            fiyat = 340;
            odemeTutari += mexicanoPizzaFiyatiKucuk;
        } else if (radOrta.isSelected()) {
            secilenBoy = "Orta";
            fiyat = 500;
            odemeTutari += mexicanoPizzaFiyatiOrta;
        } else if (radBuyuk.isSelected()) {
            secilenBoy = "Büyük";
            fiyat = 700;
            odemeTutari += mexicanoPizzaFiyatiBuyuk;
        }

        String urunBilgisi = "1x Mexicano Pizza (" + secilenBoy + ") - " + fiyat + " TL";
        sepetModeli.addElement(urunBilgisi);
        } 
    }//GEN-LAST:event_mexicanoEkleButonActionPerformed

    private void nutellaEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutellaEkleButonActionPerformed
    
    javax.swing.JRadioButton radKucuk = new javax.swing.JRadioButton("<html><b>Küçük Boy</b><br>İnce kenar, hafif lezzet<br>Fiyat: 175 TL</html>");
    javax.swing.JRadioButton radOrta = new javax.swing.JRadioButton("<html><b>Orta Boy</b><br>İdeal seçim<br>Fiyat: 250 TL</html>");
    javax.swing.JRadioButton radBuyuk = new javax.swing.JRadioButton("<html><b>Büyük Boy</b><br>Doyurucu boy, bol malzeme<br>Fiyat: 350 TL</html>");

    radKucuk.setSelected(true);

    javax.swing.ButtonGroup boyGrubu = new javax.swing.ButtonGroup();
    boyGrubu.add(radKucuk);
    boyGrubu.add(radOrta);
    boyGrubu.add(radBuyuk);

    javax.swing.JPanel panel = new javax.swing.JPanel();
    panel.setLayout(new java.awt.GridLayout(3, 1, 0, 10)); 
    panel.add(radKucuk);
    panel.add(radOrta);
    panel.add(radBuyuk);

    int sonuc = javax.swing.JOptionPane.showConfirmDialog(
        AnaEkran.this, 
        panel, 
        "Nutella Pizza Boyut Seçimi", 
        javax.swing.JOptionPane.OK_CANCEL_OPTION, 
        javax.swing.JOptionPane.PLAIN_MESSAGE
    );

    if (sonuc == javax.swing.JOptionPane.OK_OPTION) {
        String secilenBoy = "";
        if (radKucuk.isSelected()) {
            secilenBoy = "Küçük";
            fiyat = 175;
            odemeTutari += nutellaPizzaFiyatiKucuk;
        } else if (radOrta.isSelected()) {
            secilenBoy = "Orta";
            fiyat = 250;
            odemeTutari += nutellaPizzaFiyatiOrta;
        } else if (radBuyuk.isSelected()) {
            secilenBoy = "Büyük";
            fiyat = 350;
            odemeTutari += nutellaPizzaFiyatiBuyuk;
        }

        String urunBilgisi = "1x Nutella Pizza (" + secilenBoy + ") - " + fiyat + " TL";
        sepetModeli.addElement(urunBilgisi);
        } 
    }//GEN-LAST:event_nutellaEkleButonActionPerformed

    private void kizartmaEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kizartmaEkleButonActionPerformed
        fiyat = 60;
        odemeTutari += patatesKizartmasiFiyati;
        String urunBilgisi = "1x Patates Kızartması (80 gr) - " + fiyat + " TL";
        sepetModeli.addElement(urunBilgisi);      
    }//GEN-LAST:event_kizartmaEkleButonActionPerformed

    private void halkaEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halkaEkleButonActionPerformed
        fiyat = 60;
        odemeTutari += soganHalkasiFiyati;
        String urunBilgisi = "1x Soğan Halkası (10'lu) - " + fiyat + " TL";
        sepetModeli.addElement(urunBilgisi);  
    }//GEN-LAST:event_halkaEkleButonActionPerformed

    private void nuggetEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuggetEkleButonActionPerformed
        fiyat = 75;
        odemeTutari += nuggetFiyati;
        String urunBilgisi = "1x Nugget (8'li) - " + fiyat + " TL";
        sepetModeli.addElement(urunBilgisi);  
    }//GEN-LAST:event_nuggetEkleButonActionPerformed

    private void colaEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaEkleButonActionPerformed
        fiyat = 90;
        odemeTutari += colaFiyati;
        String urunBilgisi = "1x Cola (1L) - " + fiyat + " TL";
        sepetModeli.addElement(urunBilgisi); 
    }//GEN-LAST:event_colaEkleButonActionPerformed

    private void fantaEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantaEkleButonActionPerformed
        fiyat = 90;
        odemeTutari += fantaFiyati;
        String urunBilgisi = "1x Fanta (1L) - " + fiyat + " TL";
        sepetModeli.addElement(urunBilgisi); 
    }//GEN-LAST:event_fantaEkleButonActionPerformed

    private void odemeButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odemeButonuActionPerformed
        // 1. Önce kullanıcının karşısına toplam tutarı gösteren onay penceresini çıkarıyoruz
        int onay = javax.swing.JOptionPane.showConfirmDialog(
            AnaEkran.this, 
            "Toplam Ödeme Tutarınız: " + odemeTutari + " TL\nÖdemeyi onaylıyor musunuz?", 
            "Ödeme Onayı", 
            javax.swing.JOptionPane.YES_NO_OPTION, // Sadece Evet ve Hayır butonları çıkar
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        // 2. Eğer kullanıcı "Evet" (YES_OPTION) butonuna bastıysa
        if (onay == javax.swing.JOptionPane.YES_OPTION) {
        
            // Başarılı mesajı gösteriyoruz
            javax.swing.JOptionPane.showMessageDialog(
                AnaEkran.this, 
                "Ödeme başarıyla onaylanmıştır. Yine bekleriz!", 
                "İşlem Başarılı", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
        
       
         sepetModeli.clear();
         odemeTutari = 0;       
        } 
    }//GEN-LAST:event_odemeButonuActionPerformed

    private void pizzaOlusturButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaOlusturButonActionPerformed
        // 1. Kullanıcıya yönlendirme mesajı gösteriyoruz (Sadece OK/Tamam butonu olur)
        javax.swing.JOptionPane.showMessageDialog(
            AnaEkran.this, 
            "Kendi pizzanızı oluşturma ekranına yönlendiriliyorsunuz.", 
            "Bilgilendirme", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    
        // 2. Kullanıcı mesaj kutusundaki OK butonuna bastıktan sonra yeni ekran açılır
        PizzaOlusturmaEkrani yeniEkran = new PizzaOlusturmaEkrani();
        yeniEkran.setVisible(true);
    }//GEN-LAST:event_pizzaOlusturButonActionPerformed

    private void italianoBilgiButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italianoBilgiButonActionPerformed
        String pizzaBilgisi = "🍕 Italiano Pizza İçeriği:\n\n"
                        + "• Özel İtalyan Pizza Sosu\n"
                        + "• Taze Mozzarella Peyniri\n"
                        + "• Kurutulmuş Domates Dilimleri\n"
                        + "• Dilim Siyah Zeytin & Mantar\n"
                        + "• Rokalı ve İnce Kıyılmış Fesleğenli Dokunuş\n"
                        + "• Üzerinde Sızma Zeytinyağı Gezdirmesi\n\n"
                        + "👉 İtalya sokaklarındaki o meşhur butik pizzacıların kokusunu masanıza getiren gurme seçim!";

        javax.swing.JOptionPane.showMessageDialog(this, pizzaBilgisi, "Pizza Bilgisi - Italiano", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_italianoBilgiButonActionPerformed

    private void karisikBilgiButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karisikBilgiButonActionPerformed
        String pizzaBilgisi = "🍕 Karışık Pizza İçeriği:\n\n"
                        + "• Enfes Dana Sucuk & Salam\n"
                        + "• Dilim Sosis\n"
                        + "• Mantar & Mısır\n"
                        + "• Yeşil Biber & Siyah Zeytin\n"
                        + "• Bol Mozzarella ve Özel Sos\n\n"
                        + "👉 'Ben malzeme ayırt etmem, klasikten şaşmam' diyenlerin vazgeçilmez favorisi!";

    javax.swing.JOptionPane.showMessageDialog(this, pizzaBilgisi, "Pizza Bilgisi - Karışık", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_karisikBilgiButonActionPerformed

    private void turkishBilgiButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turkishBilgiButonActionPerformed
        String pizzaBilgisi = "🍕 Turkish Pizza İçeriği:\n\n"
                        + "• Bol Baharatlı Kasap Sucuğu\n"
                        + "• Küp Doğranmış Domates\n"
                        + "• İnce Tatlı Köy Biberi\n"
                        + "• Bol Eriyen Yerli Kaşar Peyniri\n"
                        + "• İsteğe Göre Üzerine Serpilen Kekik\n\n"
                        + "👉 Geleneksel damak tadımızı pizza hamuruyla buluşturan, buram buram Anadolu kokan lezzet!";

        javax.swing.JOptionPane.showMessageDialog(this, pizzaBilgisi, "Pizza Bilgisi - Turkish", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_turkishBilgiButonActionPerformed

    private void mexicanoBilgiButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mexicanoBilgiButonActionPerformed
        String pizzaBilgisi = "🍕 Mexicano Pizza İçeriği:\n\n"
                        + "• Acılı Kıymalı / Etli Sos\n"
                        + "• Acı Jalapeno Biber Dilimleri\n"
                        + "• Kırmızı Kapya Biber & Mısır\n"
                        + "• Cheddar & Mozzarella Peyniri\n"
                        + "• Özel Meksika Baharatları\n\n"
                        + "👉 Damakları çatlatan, Meksika esintili, bol acılı ve yüksek enerjili bir şölen! 🔥";

        javax.swing.JOptionPane.showMessageDialog(this, pizzaBilgisi, "Pizza Bilgisi - Mexicano", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mexicanoBilgiButonActionPerformed

    private void nutellaBilgiButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutellaBilgiButonActionPerformed
        String pizzaBilgisi = "🍫 Nutella Pizza İçeriği:\n\n"
                        + "• Taş Fırından Taze Çıkmış İncecik Pizza Tabanı\n"
                        + "• Bol Sürülebilir Orijinal Nutella\n"
                        + "• Taze Çilek ve Muz Dilimleri\n"
                        + "• Serpiştirilmiş Antep Fıstığı veya Çikolata Parçacıkları\n"
                        + "• Üzerine Pudra Şekeri Dokunuşu\n\n"
                        + "👉 Yemek sonrası tatlı krizlerini bitirecek, ezber bozan çılgın bir lezzet bombası!";

        javax.swing.JOptionPane.showMessageDialog(this, pizzaBilgisi, "Pizza Bilgisi - Nutella", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_nutellaBilgiButonActionPerformed

    private void sepetSifirlaButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepetSifirlaButonuActionPerformed
        int onay = javax.swing.JOptionPane.showConfirmDialog(
            AnaEkran.this, 
            "Yaptığınız değişiklikleri iptal edip sepeti sıfırlamak istiyor musunuz?", 
            "Ödeme Onayı", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (onay == javax.swing.JOptionPane.YES_OPTION) {
            sepetModeli.clear();
            odemeTutari = 0;  
            // Başarılı mesajı gösteriyoruz
            javax.swing.JOptionPane.showMessageDialog(
                AnaEkran.this, 
                "Sepetiniz başarıyla sıfırlanmıştır", 
                "İşlem Başarılı", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );   
        } 
    }//GEN-LAST:event_sepetSifirlaButonuActionPerformed
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AnaEkran().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aciklamaBasligi;
    private javax.swing.JLabel anabaslik;
    private javax.swing.JPanel anapanel;
    private javax.swing.JLabel cola;
    private javax.swing.JButton colaEkleButon;
    private javax.swing.JLabel colaFiyatYazisi;
    private javax.swing.JLabel colaYazi;
    private javax.swing.JLabel fanta;
    private javax.swing.JButton fantaEkleButon;
    private javax.swing.JLabel fantaFiyatYazisi;
    private javax.swing.JLabel fantaYazi;
    private javax.swing.JButton halkaEkleButon;
    private javax.swing.JLabel halkaFiyatYazisi;
    private javax.swing.JLabel italaniopizza;
    private javax.swing.JButton italianoBilgiButon;
    private javax.swing.JButton italianoEkleButon;
    private javax.swing.JLabel italianoPizzaFiyatYazisi;
    private javax.swing.JLabel italianoPizzaYazi;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton karisikBilgiButon;
    private javax.swing.JButton karisikEkleButon;
    private javax.swing.JLabel karisikPizza;
    private javax.swing.JLabel karisikPizzaFiyatYazisi;
    private javax.swing.JLabel karisikPizzaYazi;
    private javax.swing.JButton kizartmaEkleButon;
    private javax.swing.JLabel kizartmaFiyatYazisi;
    private javax.swing.JButton mexicanoBilgiButon;
    private javax.swing.JButton mexicanoEkleButon;
    private javax.swing.JLabel mexicanoPizza;
    private javax.swing.JLabel mexicanoPizzaFiyatYazisi;
    private javax.swing.JLabel mexicanoPizzaYazi;
    private javax.swing.JLabel nugget;
    private javax.swing.JButton nuggetEkleButon;
    private javax.swing.JLabel nuggetFiyatYazisi;
    private javax.swing.JLabel nuggetYazi;
    private javax.swing.JButton nutellaBilgiButon;
    private javax.swing.JButton nutellaEkleButon;
    private javax.swing.JLabel nutellaPizza;
    private javax.swing.JLabel nutellaPizzaFiyatYazisi;
    private javax.swing.JLabel nutellaPizzaYazi;
    private javax.swing.JButton odemeButonu;
    private javax.swing.JLabel patatesKizartmasi;
    private javax.swing.JLabel patatesKizartmasiYazi;
    private javax.swing.JLabel pizzaOlusturBasligi;
    private javax.swing.JButton pizzaOlusturButon;
    public static javax.swing.JList<String> sepet1;
    private javax.swing.JLabel sepetBaslik;
    private javax.swing.JLabel sepetBaslik1;
    private javax.swing.JPanel sepetPaneli;
    private javax.swing.JButton sepetSifirlaButonu;
    private javax.swing.JLabel soganHalkasi;
    private javax.swing.JLabel soganHalkasiYazi;
    private javax.swing.JButton turkishBilgiButon;
    private javax.swing.JButton turkishEkleButon;
    private javax.swing.JLabel turkishPizza;
    private javax.swing.JLabel turkishPizzaFiyatYazisi;
    private javax.swing.JLabel turkishPizzaYazi;
    // End of variables declaration//GEN-END:variables
}
